name: macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Running macOS
        run: |
          bash macos-run.sh
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          MAC_REALNAME: ${{ secrets.MAC_REALNAME }}
          MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
